### ISSUE TITLE
go-http-auth digest example only works with the hash included.

### ISSUE THREAD

**Issue by lee8oi** [abbot/go-http-auth#7]
I realize that the hash being returned on line 22 in digest.go is simply the md5 of "john:example.com:hello". So I tried creating a new hash with "bruda:example.com:hello" , changed "john" to "bruda" on line 20, and replaced the hash on line 22. But now the authentication fails & continues to ask for login info. I double checked the original hash with the same md5 tool and it matched up with "john:example.com:hello" as expected. What am I missing here?

**Comment by osiloke** [comment]
What tool did you user?
